-- -- liquibase formatted sql
--
-- -- changeset starasov:1
--
-- ALTER TABLE customer
-- ADD dialog_status varchar(20);
--
-- INSERT INTO public.customer
-- (chat_id, name)
-- SELECT 440401693, 'Тарасов Сергей'
-- WHERE NOT EXISTS(
--         SELECT id, chat_id FROM public.customer WHERE chat_id = 440401693
--     );