-- liquibase formatted sql

-- changeset alrepin:1
create table if not exists customer
(
    id          bigint generated by default as identity
        primary key,
    chat_id     bigint,
    surname     varchar(25),
    name        varchar(25),
    second_name varchar(25),
    phone       varchar(12),
    address     text
);

create table if not exists shelter
(
    id           bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    address      varchar(255),
    location_map text,
    name         varchar(255)
);

create table if not exists volunteer
(
    id          bigint generated by default as identity
        primary key,
    address     varchar(255),
    chat_id     bigint not null,
    name        varchar(255),
    phone       varchar(255),
    second_name varchar(255),
    surname     varchar(255)
);

create table if not exists info
(
    id           bigint generated by default as identity
        primary key,
    area         varchar(255),
    instructions varchar(255)
);

create table if not exists databasechangeloglock
(
    id          integer not null
        primary key,
    locked      boolean not null,
    lockgranted timestamp,
    lockedby    varchar(255)
);

create table if not exists databasechangelog
(
    id            varchar(255) not null,
    author        varchar(255) not null,
    filename      varchar(255) not null,
    dateexecuted  timestamp    not null,
    orderexecuted integer      not null,
    exectype      varchar(10)  not null,
    md5sum        varchar(35),
    description   varchar(255),
    comments      varchar(255),
    tag           varchar(255),
    liquibase     varchar(20),
    contexts      varchar(255),
    labels        varchar(255),
    deployment_id varchar(10)
);

create table if not exists breed
(
    id                    bigint generated by default as identity
        primary key,
    adult_pet_from_age    integer not null,
    breed                 varchar(255),
    recommendations_adult varchar(255),
    recommendations_child varchar(255)
);

create table if not exists pet
(
    id            bigint generated by default as identity
        primary key,
    age           integer not null,
    decision_date timestamp,
    file_path     varchar(255),
    file_size     bigint,
    media_type    varchar(255),
    name          varchar(255),
    photo         bytea,
    id_customer   bigint
        constraint fkomkj6md9m4nle48xek4gnp07s
            references customer,
    id_shelter    bigint
        constraint fk1cdg3ffovmtyr208f6q0ectxs
            references shelter,
    id_breed      bigint
        constraint fk750ldhvrm3f5uo0kw0qjinvv
            references breed
);

create table if not exists report
(
    id         bigint not null
        primary key,
    date       timestamp,
    file_path  varchar(255),
    file_size  bigint,
    media_type varchar(255),
    pet_report varchar(255),
    photo      bytea,
    id_pet     bigint
        constraint fk1kk5qc2sk2cc71fibvnto90ax
            references pet
);

-- changeset alrepin:2
INSERT INTO public.info
(id, area, instructions)
SELECT 1, 'common_info', 'Common info about bot'
    WHERE
    NOT EXISTS (
        SELECT id FROM public.info WHERE id = 1
    );