-- -- changeset starasov:2
-- INSERT INTO public.report
-- (date, id_pet, pet_report)
-- SELECT '2023-02-28 17:44:50.000000', '1', 'текст отчета 1'
-- WHERE NOT EXISTS(
--         SELECT id, pet_report FROM public.report WHERE pet_report = 'текст отчета 1'
--     );
--
-- INSERT INTO public.report
-- (date, id_pet, pet_report)
-- SELECT '2023-03-01 17:44:50.000000', '1', 'текст отчета 2'
-- WHERE NOT EXISTS(
--         SELECT id, pet_report FROM public.report WHERE pet_report = 'текст отчета 2'
--     );
--
-- INSERT INTO public.report
-- (date, id_pet, pet_report)
-- SELECT '2023-03-02 17:44:50.000000', '1', 'текст отчета 3'
-- WHERE NOT EXISTS(
--         SELECT id, pet_report FROM public.report WHERE pet_report = 'текст отчета 3'
--     );
--
